targets=edgebsd-qemu,nvmm-xl
dist=Makefile,edgebsd-qemu.in,nvmm-xl.in

#targets
[edgebsd-qemu]
type=script
script=../tools/subst.sh
depends=edgebsd-qemu.in,../tools/subst.sh
install=$(PREFIX)/libexec/EdgeBSD/edgebsd-nvmm
mode=0755

[nvmm-xl]
type=script
script=../tools/subst.sh
depends=nvmm-xl.in,../tools/subst.sh
install=$(PREFIX)/sbin
mode=0755

#dist
[edgebsd-gueststat]
install=$(PREFIX)/sbin
mode=0755
