targets=nvmm-xl
dist=Makefile,edgebsd-gueststat,nvmm-xl.in

#targets
[nvmm-xl]
type=script
script=../tools/subst.sh
depends=nvmm-xl.in,../tools/subst.sh
install=$(PREFIX)/sbin
mode=0755

#dist
[edgebsd-gueststat]
install=$(PREFIX)/sbin
mode=0755
