targets=edgebsd-gueststat,edgebsd-qemu,nvmm-update-vms,nvmm-xl
dist=Makefile,edgebsd-gueststat.in,edgebsd-qemu.in,nvmm-update-vms.in,nvmm-xl.in

#targets
[edgebsd-gueststat]
type=script
script=../tools/subst.sh
depends=edgebsd-gueststat.in,../tools/subst.sh
install=$(PREFIX)/sbin
mode=0755

[edgebsd-qemu]
type=script
script=../tools/subst.sh
depends=edgebsd-qemu.in,../tools/subst.sh
install=$(PREFIX)/libexec/EdgeBSD/edgebsd-nvmm
mode=0755

[nvmm-update-vms]
type=script
script=../tools/subst.sh
depends=nvmm-update-vms.in,../tools/subst.sh

[nvmm-xl]
type=script
script=../tools/subst.sh
depends=nvmm-xl.in,../tools/subst.sh
install=$(PREFIX)/sbin
mode=0755
