targets=edgebsd-update.8,edgebsd-update.html
dist=Makefile,docbook.sh,edgebsd-update.css.xml,edgebsd-update.xml,manual.css.xml

[edgebsd-update.8]
type=script
script=./docbook.sh
install=
depends=docbook.sh,edgebsd-update.xml

[edgebsd-update.html]
type=script
script=./docbook.sh
install=
depends=docbook.sh,edgebsd-update.css.xml,edgebsd-update.xml,manual.css.xml
