vendor=EdgeBSD
package=edgebsd-update
version=9
config=sh

subdirs=doc,src,tests
targets=tests
dist=Makefile,README.md,config.sh

#targets
[tests]
type=command
command=cd tests && (if [ -n "$(OBJDIR)" ]; then $(MAKE) OBJDIR="$(OBJDIR)tests/" "$(OBJDIR)tests/fixme.log" "$(OBJDIR)tests/shlint.log" "$(OBJDIR)tests/tests.log"; else $(MAKE) fixme.log shlint.log tests.log; fi)
depends=all
enabled=0
phony=1
