targets=edgebsd-tls.8,edgebsd-tls.html
dist=Makefile,docbook.sh,edgebsd-tls.css.xml,edgebsd-tls.xml,manual.css.xml,openssl.cnf

#targets
[edgebsd-tls.8]
type=script
script=./docbook.sh
install=
depends=docbook.sh,edgebsd-tls.xml

[edgebsd-tls.html]
type=script
script=./docbook.sh
install=
depends=docbook.sh,edgebsd-tls.css.xml,edgebsd-tls.xml,manual.css.xml

#dist
[openssl.cnf]
install=$(PREFIX)/share/doc/edgebsd-tls
