package=Hardening
version=1

targets=libHardening,hardening
cflags=-W -Wall -g -O2
ldflags=
dist=Makefile,README.md,lib.h

[libHardening]
type=library
sources=lib.c
cflags=-fPIC

[hardening]
type=binary
depends=$(OBJDIR)libHardening$(SOEXT)
sources=main.c
cflags=-fPIE
ldflags=-L$(OBJDIR). -lHardening

[lib.c]
depends=lib.h

[main.c]
depends=lib.h
