package=Hardening
version=3

targets=libHardening,hardening,true,true-relro,true-relro-now
cflags=-g
ldflags=
dist=Makefile,README.md,lib.h

[libHardening]
type=library
sources=lib.c
cflags=-fPIC
install=$(LIBDIR)

[hardening]
type=binary
depends=$(OBJDIR)libHardening$(SOEXT)
sources=hardening.c
#XXX should be added by pkgsrc itself
#cflags=-fPIE
ldflags=-L$(OBJDIR). -lHardening
install=$(BINDIR)

[lib.c]
depends=lib.h

[hardening.c]
depends=lib.h

[true]
type=binary
sources=true.c

[true-relro]
type=binary
#XXX re-use true.c directly instead
sources=true-relro.c
ldflags=-Wl,-z,relro

[true-relro-now]
type=binary
#XXX re-use true.c directly instead
sources=true-relro-now.c
ldflags=-Wl,-z,relro -Wl,-z,now
