#sample host file with the values supported

#the hardware architecture to emulate (default: native)
arch=$(uname -m)

#the hardware machine to emulate (default: 2009 PC with NVMM acceleration)
machine="q35,accel=nvmm"

#the user ID for QEMU to switch to (default: none)
user=nobody

#the directory for QEMU to chroot to (default: none)
chroot="/var/chroot/nvmm"

#number of processors to emulate (default: 1)
cpus=2

#main memory (RAM) to emulate
memory=128M

#actions
#behaviour for QEMU upon panic (default: "poweroff", or "none", "pause")
on_panic=poweroff

#behaviour for QEMU upon reboot (default: "reboot", or "shutdown")
on_reboot=shutdown

#behaviour for QEMU upon shutdown (default: "poweroff", or "pause")
on_shutdown=poweroff

#additional parameters to provide to QEMU (default: none)
args=

#section to emulate a network card (in the form "network::" ID)
[network::int0]

#the type of network device to emulate (default: "tap")
type=tap

#the interface to re-use from the host, if any (default: auto-generate)
interface=

#the MAC address to use for the interface (default: auto-generate)
mac=

#the network interface to bridge this one to (default: none)
bridge=bridge0

#driver to use for the network device (default: "virtio-net")
driver=virtio-net

#actions
#script to run upon interface creation (default: no)
on_up=no

#script to run upon interface removal (default: no)
on_down=no


#section to emulate a storage device (in the form "drive::" ID)
[drive::hd0]

#path to the file image or device node for the storage device
file=/path/to/file.img

#format of the file image on disk (default: "raw")
format=raw

#driver to use for the storage device (default: "virtio-blk-pci")
driver=virtio-blk-pci
