targets=nvmm-xl.8,nvmm-xl.html
dist=Makefile,docbook.sh,host.conf,nvmm-xl.css.xml,nvmm-xl.xml,manual.css.xml,template.netbsd.amd64

#targets
[nvmm-xl.8]
type=script
script=./docbook.sh
install=
depends=docbook.sh,nvmm-xl.xml

[nvmm-xl.html]
type=script
script=./docbook.sh
install=
depends=docbook.sh,nvmm-xl.css.xml,nvmm-xl.xml,manual.css.xml

#dist
[host.conf]
install=$(PREFIX)/share/doc/edgebsd-nvmm

[template.netbsd.amd64]
install=$(PREFIX)/share/doc/edgebsd-nvmm
